"""Type stubs for litevec."""

from typing import Any, Optional


class SearchResult:
    """A single search result."""
    id: str
    distance: float
    metadata: dict[str, Any]


class Collection:
    """A vector collection within a database."""
    @property
    def name(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    def __len__(self) -> int: ...
    def insert(self, id: str, vector: list[float], metadata: Optional[dict[str, Any]] = None) -> None: ...
    def search(self, vector: list[float], k: int = 10, filter: Optional[dict[str, Any]] = None) -> list[SearchResult]: ...
    def get(self, id: str) -> Optional[dict[str, Any]]: ...
    def delete(self, id: str) -> bool: ...
    def update_metadata(self, id: str, metadata: dict[str, Any]) -> None: ...


class Database:
    """A LiteVec vector database."""
    @staticmethod
    def open(path: str) -> "Database": ...
    @staticmethod
    def open_memory() -> "Database": ...
    def create_collection(self, name: str, dimension: int) -> Collection: ...
    def get_collection(self, name: str) -> Optional[Collection]: ...
    def delete_collection(self, name: str) -> None: ...
    def list_collections(self) -> list[str]: ...


def open(path: str) -> Database: ...
def open_memory() -> Database: ...
