"""Type stubs for litevec."""

from typing import Any, Optional


class SearchResult:
    """A single search result."""
    id: str
    distance: float
    metadata: dict[str, Any]


class Collection:
    """A vector collection within a database."""
    @property
    def name(self) -> str: ...
    @property
    def dimension(self) -> int: ...
    @property
    def distance_type(self) -> str: ...
    def __len__(self) -> int: ...
    def insert(self, id: str, vector: list[float], metadata: Optional[dict[str, Any]] = None) -> None: ...
    def insert_batch(self, items: list[tuple[str, list[float], Optional[dict[str, Any]]]]) -> int: ...
    def search(self, vector: list[float], k: int = 10, filter: Optional[dict[str, Any]] = None) -> list[SearchResult]: ...
    def text_search(self, query: str, limit: int = 10) -> list[SearchResult]: ...
    def hybrid_search(self, vector: list[float], query: str, k: int = 10) -> list[SearchResult]: ...
    def get(self, id: str) -> Optional[dict[str, Any]]: ...
    def delete(self, id: str) -> bool: ...
    def update_metadata(self, id: str, metadata: dict[str, Any]) -> None: ...
    def create_index(self, field: str) -> None: ...
    def drop_index(self, field: str) -> None: ...
    def indexed_fields(self) -> list[str]: ...


class Database:
    """A LiteVec vector database."""
    @staticmethod
    def open(path: str) -> "Database": ...
    @staticmethod
    def open_memory() -> "Database": ...
    def create_collection(self, name: str, dimension: int) -> Collection: ...
    def get_collection(self, name: str) -> Optional[Collection]: ...
    def delete_collection(self, name: str) -> None: ...
    def list_collections(self) -> list[str]: ...
    def checkpoint(self) -> None: ...
    def create_backup(self, path: str) -> None: ...
    @staticmethod
    def restore_from_backup(path: str) -> "Database": ...
    @staticmethod
    def backup_info(path: str) -> dict[str, Any]: ...


def open(path: str) -> Database: ...
def open_memory() -> Database: ...
